name: Todo Build Workflow
on:
  workflow_dispatch:

jobs:
  Print-Info:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ”” Start workflow
        run: echo "Workflow started..."

      - name: ðŸ“ƒ Show runtime context
        run: |
         echo "ðŸ“¦ Repository: ${{ github.repository }}"
         echo "ðŸŒ¿ Branch: ${{ github.ref }}"
