name: Todo Build Workflow
on:
  workflow_dispatch:

jobs:
  Print-Info:
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ”” Start workflow
        run: echo "Workflow started..."

      - name: ðŸ“ƒ Show runtime context
        run: |
         echo "ðŸ“¦ Repository: ${{ github.repository }}"
         echo "ðŸŒ¿ Branch: ${{ github.ref }}"

  build-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5.0.0

      - name: Install .NET 9
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: '9.0.x'

      - name: Build projct
        working-directory: MyTodos
        run: dotnet build
